var _ = require('underscore');
var division_codes = {
  "Yosemite":      "YO",
  "Central Coast": "CC",
  "De Anza":       "DA",
  "Diablo":        "DI",
  "East Bay":      "EB",
  "Fresno":        "FR",
  "Kern":          "KE",
  "Los Padres":    "LP",
  "Mission":       "MI",
  "North Bay":     "NB",
  "North Coast":   "NC",
  "North Valley":  "NV",
  "Peninsula":     "PE",
  "Sacramento":    "SA",
  "San Francisco": "SF",
  "Sierra":        "SI",
  "San Jose":      "SJ",
  "Stockton":      "ST"
};
	   
var priority_codes = {
  "routine": "R",
  "allgood": "N", //no trim
  "HN-Imd": "H",
  "HN-Urg": "U",
  "accelerate": "X",
  "immediate": "I"
};

var trim_codes =  {
  "Br Rmv":"BC",
  "Br Rmv+Trt":"BCS",
  "BCS Br Rmv+Trt":"BCS",
  "BC Br Rmv": "BCS",//confirm
  "Br Trim":"BT",
  "BT Br Trim":"BT",
  "C.Assist":"CON",
  "CON C.Assist":"CON",
  "FP-Rmv1 A":"F1A",
  "F1A FP-Rmv1":"F1A",
  "FP-Rmv1 B":"F1B",
  "FS-R1A+Trt":"F1C",
  "F1C FS-R1A+Trt":"F1C",
  "FS-R1B+Trt":"F1D",
  "F1D FS-R1B+Trt":"F1D",
  "FP-Rmv2 A":"F2A",
  "F2A FP-Rmv2":"F2A",
  "FP-Rmv2 B":"F2B",
  "F2B FP-Rmv2":"F2B",
  "FS-R2A+Trt":"F2C",
  "F2C FS-R2A+Trt":"F2C",
  "FS-R2B+Trt":"F2D",
  "F2D FS-R2B+Trt":"F2D",
  "FP-Rmv3 A":"F3A",
  "F3A FP-Rmv3":"F3A",
  "FP-Rmv3 B":"F3B",
  "F3B FP-Rmv3":"F3B",
  "FS-R3A+Trt":"F3C",
  "F3C FS-R3A+Trt":"F3C",
  "FS-R3B+Trt":"F3D",
  "F3D FS-R3B+Trt":"F3D",
  "FP-Rmv4 A":"F4A",
  "F4A FP-Rmv4":"F4A",
  "FP-Rmv4 B":"F4B",
  "F4B FP-Rmv4":"F4B",
  "FS-R4A+Trt":"F4C",
  "FS-R4B+Trt":"F4D",
  "F4D FS-R4B+Trt":"F4D",
  "FP-Trim A":"FAA",
  "FAA FP-Trim":"FAA",
  "FP-Trim B":"FAB",
  "FAB FP-Trim":"FAB",
  "FP-Major A":"FBA",
  "FBA FP-Major":"FBA",
  "FP-Major B":"FBB",
  "FBB FP-Major":"FBB",
  "FP-Ov A":"FOA",
  "FOA FP-Ov":"FOA",
  "FP-Ov B":"FOB",
  "FOB FP-Ov":"FOB",
  "TGR Only":"GRO",
  "TGR+SD":"GSD",
  "TGR+TD":"GTD",
  "TGR+Top":"GTO",
  "Final Ht":"HFH",
  "Overhang":"OV",
  "Rmv 1-A":"R1A",
  "R1A": "R1A",
  "Rmv 1-B":"R1B",
  "R1B": "R1B",
  "Rmv1-A+Trt":"R1C",
  "R1C":"R1C",
  "Rmv1-B+Trt":"R1D",
  "R1D":"R1D",
  "Rmv 2-A":"R2A",
  "R2A":"R2A",
  "R2B":"R2B",
  "Rmv2-A+Trt":"R2C",
  "R2C":"R2C",
  "Rmv2-B+Trt":"R2D",
  "R2D":"R2D",
  "Rmv 3-A":"R3A",
  "R3A":"R3A",
  "Rmv 3-B":"R3B",
  "R3B":"R3B",
  "Rmv3-A+Trt":"R3C",
  "R3C":"R3C",
  "Rmv3-B+Trt":"R3D",
  "R3D":"R3D",
  "Rmv 4-A":"R4A",
  "R4A":"R4A",
  "Rmv 4-B":"R4B",
  "R4B":"R4B",
  "Rmv4-A+Trt":"R4C",
  "Rmv4-B+Trt":"R4D",
  "R4D":"R4D",
  "Side":"SD",
  "side":"SD",
  "Sec Strain":"SEC",
  "Slope":"SL",
  "Srvc Drop":"SRV",
  "S-Wrap Clb":"SWC",
  "S-Wrap Lft":"SWL",
  "TopDirecti":"TD",
  "topdirect":"td",
  "Top":"TO",
  "top":"TO",
  "ReTreat":"TRT",
  //I don't know what to translate these too so this is my best guess
  "ftp":"FAA", 
  "ftpdead": "FBA"
};
var values = _.values(trim_codes);
for(var i = 0; i < values.length; i++) {
  var value = values[i];
  trim_codes[value] = value;
}

var tree_record_status = 
{
  "complete_no_issues":   "CMP_NI", 
  "complete_with_issues": "CMP_WI",  
  "contact_no_issues":    "CONTACT_NI",
  "contact_with_issues":  "CONTACT_WI",
  "tree_ok":              "OK",	        
  "open":                 "OPEN"
};

var notification_codes = {
"contact":    "C",	
"hold":       "H",	
"left_card":  "L",	
"inventory":  "N",	
"ok":         "O",	
"phone":      "P",	
"quarantine": "Q",	
"refusal":	  "R"
};

var alert_codes = {
  "other hazard":             "OH", //DISPATCHR ADDED
	"access permit":            "AP",
	"access":                   "AX",
	"bad dog":                  "BD",
	"cat 1":                    "C1",
	"cat 2":                    "C2",
	"cat 3":                    "C3",
	"dog":                      "DG",
	"environmental bmp":        "EB",
	"existing new planting":    "EP",
	"endangered species":       "ES",
	"existing trans mit plan":  "ET",
	"fire threat zone":         "FZ",
	"hoc":                      "HC",
	"concerned customer":       "IC",
	"locked gate":              "LG",
	"mid span clear":           "MC",
	"hcp mapbook zone":         "MZ",
	"nest bmp":                 "NB",
	"notify first":             "NF",
	"new planting":             "NP",
	"pi notify first":          "PI",
	"past nest review":         "PN",
	"poison-oak":               "PO",
	"past r-review":            "PP",
	"past refusal":             "PR",
	"riparian area":            "RA",
	"riparian":                 "RP",
	"tree house":               "TH",
	"mitigation plan":          "TM",
	"traffic issue":            "TR",
	"velb site":                "VS",
	"whole span clear":         "WC",
	"2014 work":                "X4",
	"2015 work":                "X5",
	"2016 work":                "X6",
	"2017 work":                "X7",
	"2018 work":                "X8",
	"2019 work":                "X9",
	"2020 work":                "Y0",
	"2021 work":                "Y1",
	"2022 work":                "Y2",
	"2023 work":                "Y3",
	"2024 work":                "Y4",
	"concurrent patrol-loc":    "YL",
	"concurrent patrol-sys":    "YS",
};

var inspection_companies = {
  "ACRT":                   "ACR",	       
  "Brenton VMS":            "BVM",	       
  "Davey Tree":             "DAV",	       
  "High Country Forestry":  "HCF",	       
  "Martinez Utility":       "MAR",	       
  "Nelson Tree":            "NEL",	       
  "Newcomb Tree Svc":       "NTS",	       
  "P.G.& E.":               "PGE",	       
  "Provco":                 "PRO",	       
  "Craig Thurber":          "THU",	       
  "Total Quality Mgmt":     "TQM",	       
  "Trees Inc.":             "TRI",	       
  "Utility Tree Service":   "UTS",	       
  "Western ECI":            "WEC",	       
  "Wright Tree":            "WRT"
};

var tree_types = {
  "Acacia":              "ACA ",	
  "Blackwood Acacia":    "ACAB",	
  "Ailanthus":           "AILA",	
  "Albizzia":            "ALBI",	
  "Alder":               "ALD ",	
  "Alder - White":       "ALDE",	
  "Alder - Red":         "ALDR",	
  "Almond":              "ALMO",	
  "Apple":               "APPL",	
  "Arundo":              "ARUN",	
  "Ash":                 "ASH ",	
  "Evergreen Ash":       "ASHE",	
  "Modesto Ash":         "ASHM",	
  "Raywood Ash":         "ASHR",	
  "Athel":               "ATHE",	
  "Australian Willow":   "AUSW",	
  "Avocado":             "AVOC",	
  "Bamboo":              "BAMB",	
  "Bay, Calif.":         "BAY ",	
  "Beech":               "BEEC",	
  "Birch":               "BIRC",	
  "Bottlebrush":         "BOTT",	
  "Brisbane Box":        "BRIS",	
  "Brush (misc)":        "BRUS",	
  "Buckeye":             "BUCK",	
  "Camphor":             "CAMP",	
  "Carob":               "CARO",	
  "Carrot Wood":         "CARW",	
  "Cascara":             "CASC",	
  "Casuarina":           "CASU",	
  "Catalpa":             "CATA",	
  "Ceanothus":           "CEAN",	
  "Cedar":               "CEDA",	
  "Atlas Cedar":         "CEDT",	
  "Century Plant":       "CENT",	
  "Cherry":              "CHER",	
  "Chestnut":            "CHES",	
  "Chinaberry":          "CHIN",	
  "Chinquapin":          "CHNQ",	
  "Coral":               "CORA",	
  "Cottonwood, Black":   "COTB",	
  "Cottonwood, Freemont": "COTT",	
  "Crape Myrtle":        "CRPE",	
  "Italian Cypress":     "CYPI",	
  "Monterey Cypress":    "CYPM",	
  "Cypress":             "CYPR",	
  "Deodara Cedar":       "DEOD",	
  "Box-Elder":           "ELDE",	
  "Elderberry":          "ELDR",	
  "Elm":                 "ELM ",	
  "Elm, American":       "ELMA",	
  "Chinese Elm":         "ELMC",	
  "Eucalyptus":          "EUCA",	
  "Blue Gum":            "EUCB",	
  "Red Gum":             "EUCC",	
  "Red-flowering Gum":   "EUCF",	
  "Coolibah":            "EUCM",	
  "Silver Dollar Gum":   "EUCP",	
  "Red Ironbark":        "EUCS",	
  "Manna Gum":           "EUCV",	
  "Eugenia":             "EUGE",	
  "Ficus":               "FICU",	
  "Fig":                 "FIG ",	
  "Fir, True":           "FIR ",	
  "Douglas Fir":         "FIRD",	
  "Grand Fir":           "FIRG",	
  "Red Fir":             "FIRR",	
  "White Fir":           "FIRW",	
  "Fruit Tree":          "FRUI",	
  "Ginkgo":              "GINK",	
  "Hackberry":           "HACK",	
  "Hawthorn":            "HAWT",	
  "Hemlock":             "HELM",	
  "Hickory":             "HICK",	
  "Jacaranda":           "JACA",	
  "Juniper":             "JUNI",	
  "Koelreuteria":        "KOEL",	
  "Laurel, Grecian":     "LAUR",	
  "Linden":              "LIND",	
  "Liq Ambar (Sw Gum)":  "LIQ ",	
  "Honey Locust":        "LOCH",	
  "Locust, Black":       "LOCU",	
  "Loquat":              "LOQ ",	
  "Madrone":             "MADR",	
  "Magnolia":            "MAGN",	
  "Bigleaf Maple":       "MAPB",	
  "Maple":               "MAPL",	
  "Silver Maple":        "MAPS",	
  "Mayten":              "MAYT",	
  "Melaleuca":           "MELA",	
  "Mesquite":            "MESQ",	
  "Mimosa":              "MIMO",	
  "Monkey Puzzle":       "MONK",	
  "Mulberry":            "MULB",	
  "Myoporum":            "MYOP",	
  "Myrtle, Pacific Wax": "MYRT",	
  "NERC Inventory":      "NERC",	
  "No Trees":            "NONE",	
  "Norfolk Island Pine": "NORF",	
  "Oak":                 "OAK ",	
  "Coast Live Oak":      "OAKC",	
  "Blue Oak":            "OAKD",	
  "Blue oak":            "OAKD",	  
  "English Oak":         "OAKE",	
  "Oregon White Oak":    "OAKG",	
  "Holly Oak":           "OAKH",	
  "Interior Live Oak":   "OAKI",	
  "Black Oak":           "OAKK",	
  "Live Oak":            "OAKL",	
  "Oracle Oak":          "OAKM",	
  "Pin Oak":             "OAKP",	
  "Red Oak, Northern":   "OAKR",	
  "Cork Oak":            "OAKU",	
  "Valley oak":          "OAKV",	  
  "Valley Oak":          "OAKV",	
  "Canyon Live Oak":     "OAKY",	
  "Oleander":            "OLEA",	
  "Olive":               "OLIV",	
  "Other":               "OTHE",	
  "Palm-Date":           "PALD",	
  "Palm-Fan":            "PALF",	
  "Palm":                "PALM",	
  "Palo Verde":          "PALO",	
  "Palm-Queen":          "PALQ",	
  "Pear":                "PEAR",	
  "Pecan":               "PECA",	
  "Pepper Tree":         "PEPP",	
  "Aleppo Pine":         "PINA",	
  "Bishop Pine":         "PINB",	
  "Canary Island Pine":  "PINC",	
  "Pine":                "PINE",	
  "Gray Pine":           "PING",	
  "Gray pine":           "PING",	  
  "Italian Stone Pine":  "PINI",	
  "Jeffery Pine":        "PINJ",	
  "Jeffery pine":        "PINJ",	
  "Knobcone Pine":       "PINK",	
  "Lodgepole Pine":      "PINL",	
  "Monterey Pine":       "PINM",	
  "Ponderosa Pine":      "PINP",	
  "Ponderosa pine":      "PINP",	  
  "Sugar Pine":          "PINU",	
  "Pistache":            "PIST",	
  "Pittosporum":         "PITT",	
  "Plum":                "PLUM",	
  "Podocarpus":          "PODO",	
  "Pomegranate":         "POME",	
  "Poplar":              "POPL",	
  "Lombardy Poplar":     "POPO",	
  "Privet":              "PRIV",	
  "Redbud":              "REDB",	
  "Redwood":             "REDW",	  
  "Redwood, Coast":      "REDW",	
  "Dawn Redwood":        "RWDD",	
  "Salt Cedar":          "SALT",	
  "Sequoia, Giant":      "SEQU",	
  "Silk Oak":            "SILK",	
  "Spruce":              "SPRU",	
  "Sycamore":            "SYCA",	
  "Tallow, Chinese":     "TALL",	
  "Tamarisk":            "TAM ",	
  "Tan Oak":             "TAN ",	
  "Toyon":               "TOYO",	
  "Tulip Tree":          "TULI",	
  "unknown":             "UNKN",	  
  "Unknown":             "UNKN",	
  null:                  "UNKN",
  "Vine":                "VINE",	
  "Black Walnut":        "WALB",	
  "English Walnut":      "WALE",	
  "Walnut":              "WALN",	
  "Willow":              "WILL",	
  "Weeping Willow":      "WILW",	
  "Yucca":               "YUCC",	
  "Zelkova":             "ZELK"
};


module.exports = {
  trim_codes: trim_codes, 
  division_codes: division_codes, 
  priority_codes: priority_codes, 
  tree_record_status: tree_record_status,
  notification_codes: notification_codes,
  alert_codes: alert_codes,
  inspection_companies: inspection_companies,
  tree_types: tree_types
};
